# .github/workflows/docker-build-test.yml
name: Docker Compose Test CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    environment: AIML_DEV

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env
        run:
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env |
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env |
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env |
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env |
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env |
          echo "S3_REGION=${{ secrets.S3_REGION }}" >> .env |
          echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" >> .env |
          echo "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}" >> .env |
          echo "DOCKER_REPO=${{ vars.DOCKER_REPO }}" >> .env |
          echo "MAX_MEMORY=${{ vars.MAX_MEMORY }}" >> .env |
          echo "DDL_PROPERTY=${{ vars.DDL_PROPERTY }}" >> .env
        shell: bash

      - name: Build containers
        run: docker compose -f docker-compose.yml build

      - name: Run containers
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for services
        run: sleep 10

      - name: Check services
        run: docker compose ps

      - name: Optional health check with retries
        run: |
          for i in {1..10}; do
            echo "Attempt $i..."
            if curl -f http://localhost:8080/test; then
              echo "Service is healthy!"
              exit 0
            fi
            echo "Not healthy yet. Retrying in 10 seconds..."
            sleep 10
          done
          echo "Service did not become healthy after 10 attempts."
          exit 1
        shell: bash

      - name: Stop containers
        run: docker compose down
